name: Lint Code Base

on: [push, pull_request]

jobs:
  codestyle:
    name: Run Codestyle checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn install

      - name: Run ESLint
        run: |
          yarn lint

      - name: Run Stylelint
        run: |
          yarn lint:scss
